export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"

export const CHANGE_AUTHOR = "CHANGE_AUTHOR"
export const GET_AUTHORS_SUCCESS = "GET_AUTHOR_SUCCESS"
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS"
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS"

export const CHANGE_PUBLISHER = "CHANGE_PUBLISHER"
export const GET_PUBLISHERS_SUCCESS = "GET_PUBLISHERS_SUCCESS"
export const CREATE_PUBLISHER_SUCCESS = "CREATE_PUBLISHER_SUCCESS"
export const UPDATE_PUBLISHER_SUCCESS = "UPDATE_PUBLISHER_SUCCESS"

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const CHANGE_USER = "CHANGE_USER"

export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const REMOVE_CUSTOMER_SUCCESS="REMOVE_CUSTOMER_SUCCESS"

export const GET_ROLEACCESS_SUCCESS = "GET_ROLEACCESS_SUCCESS"
